# Generated by Django 2.0 on 2017-12-19 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('last_name', models.CharField(max_length=100, verbose_name='Segundo Apellido')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('summary', models.TextField(help_text='Entre una breve descripcion del libro.', max_length=1000, verbose_name='Descripcion')),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para el libro en toda la Libreria', primary_key=True, serialize=False, verbose_name='ID')),
                ('imprint', models.CharField(max_length=200, verbose_name='Version')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Fecha reintegro')),
                ('status', models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('o', 'Prestado'), ('a', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad', max_length=1, verbose_name='Disponibilidad')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entre el genero del libro. Ej: Ciencia ficcion, Policiaca, Aventura, Romance, etc.)', max_length=200, verbose_name='Nombre de Genero')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Seleccione un genero para el libro.', to='catalog.Genre', verbose_name='Genero'),
        ),
    ]
