# Generated by Django 2.0 on 2017-12-27 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_auto_20171219_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Seleccione el nombre del autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Entre 13 Caracteres de <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Entre el Lenguaje', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language', verbose_name='Lenguaje'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Entre el titulo del libro', max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(help_text='Seleccione el libro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book', verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Entre la fecha de reintegro', null=True, verbose_name='Fecha reintegro'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(help_text='Entre la version', max_length=200, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Mantenimiento'), ('o', 'Prestado'), ('a', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Seleccione la Disponibilidad', max_length=1, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Entre el lenguaje natural del libro. (Ej: Ingles, Frances, Japanes, etc)', max_length=200, verbose_name='Nombre Lenguaje'),
        ),
    ]
